### ISSUE TITLE
[Meta] Enhance current search functionality on opensearch.org with results landing page

### ISSUE THREAD

**Issue by zelinh** [opensearch-project/project-website-search#65]
The search functionality in opensearch.org website was integrated on the top right corner of the opensearch.org website page. The results were shown in a dropdown menu which is difficult for user to browse and navigate to the intended searched page. 

We plan to add a results landing page that is a individual webpage that shows the search results clearly and give user more options to filter out search results.

- [x] Enable the API infra to support filter parameters such as version, search file type.
- [x] Create a search page to display results.
- [x] #66
- [ ] ~Integrate forum search results to the search landing page.~

**Comment by zelinh** [comment]
We firstly launched the results landing page here. https://github.com/opensearch-project/documentation-website/pull/7942

**Comment by zelinh** [comment]
Close this issue as it's completed.
